### ISSUE TITLE
PreviewUrl in MailingDetail is always empty

### ISSUE THREAD

**Issue by NickHatBoecker** [SC-Networks/evalanche-soap-api-struct#35]
Hey there,

I need to use the api, because the old XML RPC Api will be shut down soon. So I updated my code accordingly.
FYI: I want to implement an archive page, listing all sent mailings with a link to the preview.

I'm calling `getByTypeId(67, $mandatorId)` from `MailingClientInterface` in order to get all sent mailings.

With the old XMLRPC Api I got a `previewUrl` for all the mailings I received. But with the new soap API the `previewUrl` in `MailingDetail` is always empty. Is this a bug or a feature? :D

Best regards
Nick

**Comment by WorksDev** [comment]
Hi @NickHatBoecker 

this is an internal problem - will be fixed within the next week.
