### ISSUE TITLE
XMLRPC -> Soap: How to get HTML Preview Url?

### ISSUE THREAD

**Issue by NickHatBoecker** [SC-Networks/evalanche-soap-api-struct#36]
Hey there,

thank you again for the fixes last week. Unfortunately I have one more question :/

Again for the context: I'm upgrading from XMLRPC API to the new soap API. I'm implementing a newsletter archive.
I'm calling `getByTypeId(67, $mandatorId)` from `MailingClientInterface` in order to get all sent mailings and use the `previewUrl` as a link to the sent newsletter.

In the XMLRPC API the link was a complete HTML version of the newsletter. In the new soap API it's only a preview image (not even a full version) of the newsletter.

- `previewUrl` in XMLRPC: https://scnem.com/art_resource.php?sid=enemb.2oi2nm1,f=999
- `previewUrl` in soap: https://scnem.com/resource_preview.php?sid=enemb.2oi2nm1,f=999

Was this HTML preview removed in the soap API or is there another way to get the link to this one?

Thanks in advance.

Best regards
Nick

**Comment by WorksDev** [comment]
Hi @NickHatBoecker,

~~sry for that - the url was a misinterpretation of "PreviewUrl" - we will output the same url as in the XMLRPC interface.~~

@NickHatBoecker
You can take the value of Url from the result. Preview Url is still output with a thumbnail Url

**Comment by usox** [comment]
@NickHatBoecker 
But beware, the `url` property in `MailingDetail` contains - due to historical reasons - a relative uri and not an absolute one.

**Comment by NickHatBoecker** [comment]
Thank you @WorksDev and @usox. The `url` property works perfectly fine.
